services:
  brezzely-backend:
    image: brezzly/breezely-backend:latest
    command: gunicorn breezelybackend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - path: ./.env.docker
        required: true # default
    environment:
      SQL_HOST: ${SQL_HOST}
      DEBUG: 1
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      SQL_DATABASE: ${SQL_DATABASE} 
      DATABASE: ${DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD} 
      SQL_PORT: ${SQL_PORT}
      ZITADEL_CLIENT_ID: ${ZITADEL_CLIENT_ID} 
      ZITADEL_DOMAIN: ${ZITADEL_DOMAIN}
      ZITADEL_ISSUER_URL: ${ZITADEL_ISSUER_URL}
      ZITADEL_INTROSPECTION_URL: ${ZITADEL_INTROSPECTION_URL}
      ZITADEL_JWKS_ENDPOINT: ${ZITADEL_JWKS_ENDPOINT}
      ZITADEL_TOKEN_URL: ${ZITADEL_TOKEN_URL}
      API_PRIVATE_KEY_FILE_PATH: ${API_PRIVATE_KEY_FILE_PATH}
      THINGSBOARD_URL: ${THINGSBOARD_URL}
      THINGSBOARD_USER_EMAIL: ${THINGSBOARD_USER_EMAIL}
      THINGSBOARD_USER_PASSWORD: ${THINGSBOARD_USER_PASSWORD}
    ports:
      - ${EXTERNAL_PORT}:8000