version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./volumes/.mytb-data:/data
      - ./volumes/.mytb-logs:/var/log/thingsboard
 
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    env_file: '.env.docker'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8081:8080'
  
  db:
    restart: 'always'
    image: postgres:16-alpine
    env_file: '.env.docker'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'