# Generated by Django 5.1.3 on 2024-12-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_expo_push_token_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thingsboard_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('device_id',), name='unique_device_id'),
        ),
    ]
