# Generated by Django 5.1.3 on 2024-12-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_thingsboard_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
